const ALL_CHARACTERS = [
    {
        nombre: "Amador Rivas",
        tipo: "Principal",
        apodo: "Cuqui",
        genero: ["Masculino"],
        hijos: 5,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Garaje", "Caravana", "Bajo A", "1º B", "2º A"],
        piso_contubernio: ["3º Int. Der.", "3º Int. Izq."],
        ocupacion: ["Banquero", "Gigoló", "Vendedor", "Vigilante", "Payaso", "Desempleado", "Hombre florero", "Varios trabajos"],
        presidente: true,
        temporadaAparicion: 1,
        frase: ["¡Si no tengo ganas de na, ¡Na más que de morirme!"],
        emoji: "🦁🕺🕵️‍♂️🦸‍♂️",
    },
    {
        nombre: "Maite Figueroa",
        tipo: "Principal",
        apodo: "Cuqui",
        genero: ["Femenino"],
        hijos: 4,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "1º A", "2º A"],
        piso_contubernio: ["2º Ext. Izq."],
        ocupacion: ["Vendedor", "Masajista", "Escritor", "Ladrón", "Exconvicto", "Camarera"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¡Me caigo muerta!"],
        emoji: "👩🏼🦔🤰👚",
    },
    {
        nombre: "Teodoro Rivas",
        tipo: "Principal",
        apodo: "DJ Theo",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Bajo A", "1º C", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Pescadero", "DJ", "Vendedor"],
        presidente: false,
        temporadaAparicion: 7,
        frase: ["¡Te voy a poner slim philippine!"],
        emoji: "🎧🦽🪩💿",
    },
    {
        nombre: "Justiniana Latorre",
        tipo: "Secundario",
        apodo: "Maitechu",
        genero: ["Femenino"],
        hijos: 12,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Bajo A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 5,
        frase: ["Maitechu, lo que tienes que hacer es volver con mi hijo."],
        emoji: "👵💶🤬✋",
    },
    {
        nombre: "Antonio Recio",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Caravana", "Bajo B", "1º C"],
        piso_contubernio: ["Bajo Int. Izq.", "3º Ext. Izq."],
        ocupacion: ["Pescadero", "Empresario", "Marqués"],
        presidente: true,
        temporadaAparicion: 1,
        frase: ["En esta comunidad, ¡Yo soy la ley!"],
        emoji: "🦞🚛🔌🔫",
    },
    {
        nombre: "Berta Escobar",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["1º C", "2º C"],
        piso_contubernio: ["Bajo Int. Izq.", "3º Ext. Izq."],
        ocupacion: ["Pescadero", "Monja", "Ama de casa"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¡Arderéis en el caldero de Satán!"],
        emoji: "⛪️🛐👩‍❤️‍👩👩🏼‍❤️‍💋‍👨🏿",
    },
    {
        nombre: "Alba Recio",
        tipo: "Principal",
        apodo: "Alvaro Recio",
        genero: ["Masculino", "Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Bajo B", "1º C", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Repostería [Oficio/Servicio]", "Monja"],
        presidente: false,
        temporadaAparicion: 8,
        frase: ["¡¡¡Jurásica, Neandertala, Pleistocénica!!!"],
        emoji: "🏳‍⚧🧁👩🏻🍰",
    },
    {
        nombre: "Violeta Recio",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º C"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Pescadero", "Monja", "Internada"],
        presidente: false,
        temporadaAparicion: 2,
        frase: ["¿Una limosna para los pobres del mundo?"],
        emoji: "🔪🤪💊🛸",
    },
    {
        nombre: "Rosario Parrales",
        tipo: "Secundario",
        apodo: "Parrales",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Colombia",
        piso_montepinar: ["Fuera", "1º C"],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Pescadero", "Varios trabajos", "Empresario"],
        presidente: true,
        temporadaAparicion: 4,
        frase: ["¡Es el sueño español!"],
        emoji: "🇨🇴🦐🚛👰🏽‍♂",
    },
    {
        nombre: "Mamasita Parrales",
        tipo: "Esporádico",
        apodo: "Luz Marina Montoya",
        genero: ["Femenino"],
        hijos: 1,
        origen: "Colombia",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Exconvicto", "Traficante"],
        presidente: false,
        temporadaAparicion: 5,
        frase: ["¡Ay virgencita, me va a hacer vudú!"],
        emoji: "🇨🇴🛫👵🏾💩",
    },
    {
        nombre: "Manolita",
        tipo: "Episódico",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "Colombia",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Ladrón", "Desempleado"],
        presidente: false,
        temporadaAparicion: 5,
        frase: ["Ay muchas gracias, es tan generoso centollito..."],
        emoji: "🇨🇴👯‍♀💶👩🏽",
    },
    {
        nombre: "Javier Maroto",
        tipo: "Principal",
        apodo: "Pelocho",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º B", "Ático B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Informático", "Conserje"],
        presidente: true,
        temporadaAparicion: 1,
        frase: ["Ay Lola, Lola, tu nombre me mola..."],
        emoji: "👨‍💻🧑🏻‍🦱👩🏼‍💼🥚",
    },
    {
        nombre: "Lola Trujillo",
        tipo: "Principal",
        apodo: "Chihuaha",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Ático B"],
        piso_contubernio: ["1º Int. Der.", "2º Ext. Izq."],
        ocupacion: ["Fotógrafo", "Actor"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¡Quita, egoista, me he enfadado!"],
        emoji: "🧛‍♀📸🎭🎥",
    },
    {
        nombre: "Vicente Maroto",
        tipo: "Principal",
        apodo: "Hombre cojín",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["2º B", "Ático B"],
        piso_contubernio: ["2º Int. Izq."],
        ocupacion: ["Jubilado"],
        presidente: true,
        temporadaAparicion: 1,
        frase: ["Eehh, ¡Caña aquí!"],
        emoji: "🛋📺⚽🍺",
    },
    {
        nombre: "Estela Reynolds",
        tipo: "Principal",
        apodo: "Paca Pacheco",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo A", "Ático B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Actor"],
        presidente: false,
        temporadaAparicion: 3,
        frase: ["¡Oh! ¡Qué ataque más gratuito!"],
        emoji: "🥃🎭📽🥴",
    },
    {
        nombre: "Fermín Trujillo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º B", "Ático B"],
        piso_contubernio: ["2º Int. Der.", "3º Ext. Der."],
        ocupacion: ["Espetero", "Camarero", "Empresario", "Payaso", "Conserje"],
        presidente: false,
        temporadaAparicion: 6,
        frase: ["To las locas del coño, ¡pa mí!"],
        emoji: "🐟🛶👨🍺",
    },
    {
        nombre: "Gregoria Gutiérrez",
        tipo: "Principal",
        apodo: "Doña Croqueta",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["2º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¡Marido cojín!"],
        emoji: "👩‍🍳🥘⚰👩‍🦱",
    },
    {
        nombre: "Martina",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Ático B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Masajista", "Terapeuta"],
        presidente: false,
        temporadaAparicion: 11,
        frase: ["Tu cuerpo te esta hablando..."],
        emoji: "👩💆‍♀️🤱👨🏻‍🦱",
    },
    {
        nombre: "Gabi",
        tipo: "Esporádico",
        apodo: "Javi",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Informático", "Empresario"],
        presidente: false,
        temporadaAparicion: 7,
        frase: ["¡Easy date es todo un éxito!"],
        emoji: "🤑💻💪😁",
    },
    {
        nombre: "Enrique Pastor",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo B", "Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        presidente: true,
        temporadaAparicion: 1,
        frase: ["Aquí hay tema... ¡Pero vamos!"],
        emoji: "👨🏻‍🦲📚🏛️🐬",
    },
    {
        nombre: "Araceli Madariaga",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B", "1º C", "2º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Peluquero", "Masajista", "Ama de casa"],
        presidente: true,
        temporadaAparicion: 1,
        frase: ["Yo me enamoro de almas, no de genitales..."],
        emoji: "👩‍❤️‍👩🍃🕉️🇳🇵",
    },
    {
        nombre: "Judith Becker",
        tipo: "Principal",
        apodo: "Cuchufleta",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B", "Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Psicólogo"],
        presidente: true,
        temporadaAparicion: 3,
        frase: ["No atiendo sin cita previa..."],
        emoji: "👩‍🦰👴🏻👩‍⚕🦒",
    },
    {
        nombre: "Reyes Ballesteros",
        tipo: "Principal",
        apodo: "Lesbiana",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Dentista"],
        presidente: false,
        temporadaAparicion: 5,
        frase: ["Este mundo está lleno de homófobos de mierda."],
        emoji: "🦷👩‍🦰💪🏳‍🌈",
    },
    {
        nombre: "Julián Pastor",
        tipo: "Secundario",
        apodo: "Viejo verde",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["Tu deja los estudios a un lado lo más importante ahora es que pierdas tu virginidad."],
        emoji: "👴🏻🦽👯‍♀💶",
    },
    {
        nombre: "Matthew Edwards",
        tipo: "Esporádico",
        apodo: "Fuck fuck fuck",
        genero: ["Masculino"],
        hijos: 2,
        origen: "Estados Unidos",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        presidente: false,
        temporadaAparicion: 4,
        frase: ["Quitó camiseto, y tenia pezones duros como piedros..."],
        emoji: "🇺🇸👨🏼‍🦱☠🇵🇭",
    },
    {
        nombre: "Menchu Carrascosa",
        tipo: "Principal",
        apodo: "Tanqueta",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Ático A"],
        piso_contubernio: ["1º Ext. Der.", "3º Int. Izq."],
        ocupacion: ["Jubilado", "Ama de casa", "Traficante"],
        presidente: true,
        temporadaAparicion: 9,
        frase: ["¡Cómeme las tetas!"],
        emoji: "👩🛒🍳👜",
    },
    {
        nombre: "Yolanda Morcillo",
        tipo: "Principal",
        apodo: "Yoli Morcillo",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Ático A", "2º A"],
        piso_contubernio: ["1º Ext. Der.", "3º Int. Izq."],
        ocupacion: ["Diseñador", "Traficante", "Influencer"],
        presidente: true,
        temporadaAparicion: 9,
        frase: ["¡Que yo estoy enamorada, y cuando estoy enamorada soy MUY peligrosa!"],
        emoji: "👩🛍👗🧵",
    },
    {
        nombre: "Josito Morcillo",
        tipo: "Secundario",
        apodo: "José Morcillo",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera", "Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desempleado", "Traficante"],
        presidente: false,
        temporadaAparicion: 9,
        frase: ["¿Te gusta el porno? Tengo 4 teras."],
        emoji: "✖📁💻🧻",
    },
    {
        nombre: "Moroso",
        tipo: "Secundario",
        apodo: "Germán Palomares",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º C"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["Vecinos, iros a tomar por culo."],
        emoji: "👤❓💰💼",
    },
    {
        nombre: "Fina Palomares",
        tipo: "Principal",
        apodo: "Doña Fina",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["2º C"],
        piso_contubernio: ["2º Int. Der."],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 8,
        frase: ["¡¿Qué hablais de mí?!"],
        emoji: "🪑👵🏻🐈😈",
    },
    {
        nombre: "Clarita Gutiérrez",
        tipo: "Principal",
        apodo: "Clara Gutiérrez",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera", "2ºA"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Conserje", "Sirviente", "Pescadero", "Desempleado"],
        presidente: false,
        temporadaAparicion: 10,
        frase: ["Es que si no me lo explicas bien…"],
        emoji: "👩🧹🤱🛒",
    },
    {
        nombre: "Nines Chacón",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Sirviente", "Camarero", "Desempleado"],
        presidente: false,
        temporadaAparicion: 2,
        frase: ["¡No ni ná!"],
        emoji: "🤰🛋📺💃",
    },
    {
        nombre: "Raquel Villanueva",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor", "Camarero", "Wedding planner"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¡Que no son operadas!"],
        emoji: "👩🏼‍💼🍈🍈💍",
    },
    {
        nombre: "Rebeca Ortiz",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Ático A"],
        piso_contubernio: ["1º Ext. Der."],
        ocupacion: ["Abogado"],
        presidente: false,
        temporadaAparicion: 7,
        frase: ["Yo te llevo el divorcio."],
        emoji: "👱‍♀👩🏼‍💼👩🏼‍⚖💼",
    },
    {
        nombre: "Blanca Neruda",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        presidente: false,
        temporadaAparicion: 2,
        frase: ["Si me subes el correo te recibo en lencería."],
        emoji: "👩💼👢👙",
    },
    {
        nombre: "Coque Calatrava",
        tipo: "Principal",
        apodo: "Coke",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Caravana", "Bajo B", "1º A"],
        piso_contubernio: ["Portería"],
        ocupacion: ["Jardinero", "Conserje", "Camarero", "Yonki", "Cómico"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["Una cosilla que se me viene a la mente..."],
        emoji: "🌲🚬🧹🩻",
    },
    {
        nombre: "Maxi Angulo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Caravana", "Bajo B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Conserje", "Camarero"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¡Atrás! ¡No me obligues a hacerte el molinillo!"],
        emoji: "🦁🍻🧠🥶",
    },
    {
        nombre: "José Ignacio",
        tipo: "Esporádico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Abogado"],
        presidente: false,
        temporadaAparicion: 7,
        frase: ["Este juicio esta ganado A-Arturo, Amador."],
        emoji: "👨‍⚖💼📄📃",
    },
    {
        nombre: "Mari Tere Valverde",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 3,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["Te he preparado un bizcocho."],
        emoji: "👵🎂🗣📓",
    },
    {
        nombre: "Izaskun Sagastume",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¡Movida, movida!"],
        emoji: "🚬👵🥃📓",
    },
    {
        nombre: "Bruno Quiroga",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Bajo B", "1º B"],
        piso_contubernio: ["3º Ext. Der."],
        ocupacion: ["Pianista", "Artista"],
        presidente: true,
        temporadaAparicion: 9,
        frase: ["¡Que me hizo un Boris Becker!"],
        emoji: "🤵🎹🎶🏆",
    },
    {
        nombre: "Cristina Aguilera",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["Soy comercial de una agencia de viajes, no prostituta."],
        emoji: "",
    },
    {
        nombre: "Leonardo Romaní",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor", "Empresario"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["Que me debes 50000€ euros."],
        emoji: "🤓🎮💰💻",
    },
    {
        nombre: "Ongombo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "África",
        piso_montepinar: ["1º C"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Conserje", "Pescadero", "Sirviente"],
        presidente: false,
        temporadaAparicion: 10,
        frase: ["¡Tu culo de negra, eh!"],
        emoji: "🇨🇬👨🏿💪🏿👩🏼‍❤‍💋‍👨🏿",
    },
    {
        nombre: "Sergio Arias",
        tipo: "Principal",
        apodo: "Doctor Ventura",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo A", "Ático A"],
        piso_contubernio: ["3º Ext. Der."],
        ocupacion: ["Actor"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¿Ves esa estrella? Ahora lleva tu nombre."],
        emoji: "🎥🕴👨‍⚕🩺",
    },
    {
        nombre: "Joaquin Arias",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["Habléme sin tapujos Doctor Ventura..."],
        emoji: "",
    },
    {
        nombre: "Bibiana",
        tipo: "Esporádico",
        apodo: "Travesti",
        genero: ["Masculino", "Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Prostituta"],
        presidente: false,
        temporadaAparicion: 8,
        frase: ["El tiburón no me lo corto porque es mi herramienta de trabajo"],
        emoji: "🧔🏼‍♀👮‍♂🏳‍⚧⚧",
    },
    {
        nombre: "Agustín Gordillo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º A"],
        piso_contubernio: ["3º Int. Der."],
        ocupacion: ["vendedor de filtros de agua"],
        presidente: false,
        temporadaAparicion: 11,
        frase: ["Lo veo todo por un agujerito."],
        emoji: "👷‍♂️👩‍⚕️👨‍🏭👨‍⚕️",
    },
    {
        nombre: "Alcaldesa",
        tipo: "Secundario",
        apodo: "María Teresa",
        genero: ["Femenino"],
        hijos: 3,
        origen: "España",
        piso_montepinar: ["Fuera", "Bajo B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        presidente: false,
        temporadaAparicion: 8,
        frase: ["¡Fuera pajarraco malo, fuera!"],
        emoji: "👵🏻🏛🐦‍⬛👜",
    },
    {
        nombre: "Señor ministro",
        tipo: "Esporádico",
        apodo: "Alejandro Echevarria",
        genero: ["Masculino"],
        hijos: 3,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        presidente: false,
        temporadaAparicion: 8,
        frase: ["Enrique, me has fallado 3 veces, no me falles 4..."],
        emoji: "🤵💼💿🏛️",
    },
    {
        nombre: "Raluca Petrescu",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "Rumanía",
        piso_montepinar: ["Fuera", "Bajo A", "Ático B"],
        piso_contubernio: ["2º Int. Der."],
        ocupacion: ["Prostituta", "Pescadera", "Masajista", "Sirviente"],
        presidente: false,
        temporadaAparicion: 6,
        frase: ["¡Ay, Fermín! '¡hasme tulia' otra vez!"],
        emoji: "🇷🇴🚺🍔🍕",
    },
    {
        nombre: "Chusa",
        tipo: "Principal",
        apodo: "La Chusa",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "Bajo A", "Ático A"],
        piso_contubernio: ["3º Ext. Izq.", "1º Int. Der."],
        ocupacion: ["Prostituta", "Yonki", "Sirviente"],
        presidente: false,
        temporadaAparicion: 4,
        frase: ["¡¿A qué te pincho?!"],
        emoji: "🔪💉💸👯‍♀",
    },
    {
        nombre: "Cabeza nido",
        tipo: "Secundario",
        apodo: "Héctor",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "Bajo A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Artista", "Hombre florero"],
        presidente: false,
        temporadaAparicion: 9,
        frase: ["Voy a hacer mi opera prima: 'El hombre y la mierda'."],
        emoji: "👤🪹🎨👨‍🎨",
    },
    {
        nombre: "Cecilio el terapeuta",
        tipo: "Esporádico",
        apodo: "Argentino",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Argentina",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Psicólogo", "Terapeuta"],
        presidente: false,
        temporadaAparicion: 7,
        frase: ["Tienes que abrazar tu soledad iluminadora..."],
        emoji: "🇦🇷👨‍⚕📝🤔",
    },
    {
        nombre: "Rosanna",
        tipo: "Secundario",
        apodo: "Rosana",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Prostituta"],
        presidente: false,
        temporadaAparicion: 11,
        frase: ["Mejor damelo todo en cash que esto me pilla muy lejos."],
        emoji: "",
    },
    {
        nombre: "Padre Alejandro",
        tipo: "Secundario",
        apodo: "Alejandro Ledesma",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Sacerdote"],
        presidente: false,
        temporadaAparicion: 5,
        frase: ["¡Antonio has metido un arma en la casa del señor!"],
        emoji: "⛪🙏👬👨‍❤️‍💋‍👨",
    },
    {
        nombre: "Mario Vaquerizo",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Actor", "Representante"],
        presidente: false,
        temporadaAparicion: 6,
        frase: ["Venga cariño, tira la foto que tengo prisa..."],
        emoji: "",
    },
    {
        nombre: "Pascual",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vigilante"],
        presidente: false,
        temporadaAparicion: 2,
        frase: ["¡Violación del perímetro!"],
        emoji: "🔫👮🏻‍♂👆🔪",
    },
    {
        nombre: "Edurne Sagastume",
        tipo: "Esporádico",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        presidente: false,
        temporadaAparicion: 7,
        frase: ["Te voy a echar un polvo que te voy a doblar."],
        emoji: "",
    },
    {
        nombre: "Naserbin Khalid Al-Faisal",
        tipo: "Episódico",
        apodo: "Jeque árabe",
        genero: ["Masculino"],
        hijos: 1,
        origen: "Árabe",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jeque", "Traficante"],
        presidente: false,
        temporadaAparicion: 3,
        frase: ["Nice to meet you Antonio my friend!"],
        emoji: "🕌🇦🇪👳🏾‍♂💰",
    },
    {
        nombre: "Maharamindri Baba",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Argentina",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Sacerdote"],
        presidente: false,
        temporadaAparicion: 3,
        frase: ["¡¿Hermanos oís la voz?!"],
        emoji: "🇦🇷🙏💰🛸",
    },
    {
        nombre: "Miguel",
        tipo: "Esporádico",
        apodo: "Director internado sangriento",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Director"],
        presidente: false,
        temporadaAparicion: 4,
        frase: ["¿Amigo yo? ¿De un actor?"],
        emoji: "👨😡🎬🎭",
    },
    {
        nombre: "Minguito",
        tipo: "Secundario",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Fuera"],
        piso_contubernio: ["3º Ext. Izq."],
        ocupacion: ["Desempleado", "Conserje"],
        presidente: false,
        temporadaAparicion: 9,
        frase: ["¡Te desafío!"],
        emoji: "",
    },
    {
        nombre: "Carmelito",
        tipo: "Esporádico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Hijo putaaa... me has mataooo..."],
        piso_contubernio: ["3º Ext. Izq.", "1º Int. Der."],
        ocupacion: ["Yonki"],
        presidente: false,
        temporadaAparicion: 7,
        emoji: "",
    },
    {
        nombre: "Suliman",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "África",
        piso_montepinar: ["Fuera"],
        frase: ["¡Fermín cabrón! Tu debes 20€"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        presidente: false,
        temporadaAparicion: 6,
        emoji: "",
    },
    {
        nombre: "Ramón Rivas",
        tipo: "Esporádico",
        apodo: "Padre amador",
        genero: ["Masculino"],
        hijos: 12,
        origen: "España",
        piso_montepinar: ["Villazarcillo"],
        frase: ["Amador, soy gay."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 5,
        emoji: "",
    },
    {
        nombre: "Fabio Sabatani",
        tipo: "Esporádico",
        apodo: "Peluquero",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Argentina",
        piso_montepinar: ["Fuera"],
        frase: ["Se me deprimió la becaria..."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Peluquero"],
        presidente: false,
        temporadaAparicion: 1,
        emoji: "👨💈✂🇦🇷",
    },
    {
        nombre: "Silvio",
        tipo: "Principal",
        apodo: "Okupa",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Cuba",
        piso_montepinar: ["1º A"],
        frase: ["¡Ay, Chocho!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Camarero", "Desempleado"],
        presidente: false,
        temporadaAparicion: 1,
        emoji: "👬🏳️‍🌈🛍🐕",
    },
    {
        nombre: "Hakim",
        tipo: "Episódico",
        apodo: "Marroquí",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Árabe",
        piso_montepinar: ["Fuera"],
        frase: ["Perdone señor, pero no tengo que aguantar su intolerancia."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        presidente: false,
        temporadaAparicion: 3,
        emoji: "",
    },
    {
        nombre: "Eric Cortés",
        tipo: "Secundario",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Mujeres hay muchas, hermanos solo tienes uno."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        presidente: false,
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Sandra Espinosa",
        tipo: "Secundario",
        apodo: "Becaria",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Araceli, la señora del secador no se mueve..."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Peluquero", "Camarero", "Prostituta"],
        presidente: false,
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Charo",
        tipo: "Secundario",
        apodo: "Doña Charo",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B"],
        frase: ["¡Qué no hay papel!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Barbara",
        tipo: "Secundario",
        apodo: "Teacher cajadientes",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["¡Dame más duro contra el mapa de España!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Profesor"],
        presidente: false,
        temporadaAparicion: 10,
        emoji: "👩‍🏫🦷🗺👦",
    },
    {
        nombre: "Sonia",
        tipo: "Esporádico",
        apodo: "La klingon",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "2º C"],
        frase: ["Tu hijo me ha quemado el pelo, los niños me llaman la Freddy Krueger."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Profesor"],
        presidente: false,
        temporadaAparicion: 10,
        emoji: "👩‍🏫🧪🥼🙍‍♀️",
    },
    {
        nombre: "Gigi Diamond",
        tipo: "Episódico",
        apodo: "Marta",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["¡No! Llámame Marta, ____ es un nombre demasiado sucio para que lo utilice mi novio..."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Actriz"],
        presidente: false,
        temporadaAparicion: 5,
        emoji: "🎭👠💎💎",
    },
    {
        nombre: "Tomás",
        tipo: "Esporádico",
        apodo: "Gay Lola",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["¡Nosotras parimos, nosotras decidimos!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Estilista", "Representante"],
        presidente: false,
        temporadaAparicion: 3,
        emoji: "🎭🏳️‍🌈👬💄",
    },
    {
        nombre: "Alcalde",
        tipo: "Secundario",
        apodo: "Juan Antonio Valbuena",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Te presento a mi perro, Jose Mari"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        presidente: false,
        temporadaAparicion: 3,
        emoji: "🤵🐕🏛️⛓",
    },
    {
        nombre: "Luis Ángel",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º C"],
        frase: ["¿Cuando os he dicho que me iba a la India?"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Informático"],
        presidente: false,
        temporadaAparicion: 3,
        emoji: "👨💻🧳🇮🇳",
    },
    {
        nombre: "Francisco Javier",
        tipo: "Principal",
        apodo: "Fran",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B"],
        frase: ["¡Cómeme el rabo!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Estudiante", "Camarero"],
        presidente: false,
        temporadaAparicion: 1,
        emoji: "🚬☘🛵👦🏻",
    },
    {
        nombre: "Patu",
        tipo: "Esporádico",
        apodo: "Tetas de goma",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Maite, conozco un abogado buenísimo."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Ama de casa"],
        presidente: false,
        temporadaAparicion: 1,
        emoji: "👩🍈🍈💃",
    }
    ,
    {
        nombre: "Eulogia Sarrión",
        tipo: "Principal",
        apodo: "Logi",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["1º Ext. Izq.", "3º Ext. Der."],
        ocupacion: ["Ama de casa"],
        presidente: false,
        temporadaAparicion: 13,
        frase: ["Señora, el vídeoclub lo cerraron hace 10 años."],
        emoji: "👵🧹🗣👑",
    },
    {
        nombre: "Alonso Martínez",
        tipo: "Principal",
        apodo: "Alons",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Izq."],
        ocupacion: ["Empresario", "Vendedor"],
        presidente: false,
        temporadaAparicion: 13,
        frase: ["Cieluchi deberías llevarte bien con Inma por los niños."],
        emoji: "🛏💰🩲👨",
    },
    {
        nombre: "Greta Garmendia",
        tipo: "Principal",
        apodo: "La thunber",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Der."],
        ocupacion: ["Farmacéutica"],
        presidente: true,
        temporadaAparicion: 13,
        frase: ["No pasa nada, soy una persona con un gran sentido del humor, a pesar de tener un palo de fregona metido por el culo."],
        emoji: "👩‍⚕️💊🦌👪",
    },
    {
        nombre: "Esteban Guijarro",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Der."],
        ocupacion: ["Inspector de hacienda"],
        presidente: false,
        temporadaAparicion: 13,
        frase: ["Yo mientras no se drogue..."],
        emoji: "🤵💰💼🩲",
    },
    {
        nombre: "Julia Guijarro Garmendia",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Der."],
        ocupacion: ["Estudiante", "Especuladora"],
        presidente: false,
        temporadaAparicion: 13,
        frase: ["Vosotros decidistéis comprar mi virginidad, quiero el bajo a mi nombre"],
        emoji: "",
    },
    {
        nombre: "Cristina Sanromán",
        tipo: "Principal",
        apodo: "Mami pechotes",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Bajo Int. Der."],
        ocupacion: ["Dentista"],
        presidente: false,
        temporadaAparicion: 14,
        frase: ["Oye no te me pongas decinómonico eh, que ya te hemos pedido perdón."],
        emoji: "🤱🍼🍼🦷",
    },
    {
        nombre: "Martín Segurola",
        tipo: "Principal",
        apodo: "Cocinillas, tostas",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Bajo Int. Der."],
        ocupacion: ["Cocinero"],
        presidente: true,
        temporadaAparicion: 14,
        frase: ["Te dije que era muy pronto para llevarla a la guardería"],
        emoji: "🤒👨‍🍳🍳👶",
    },
    {
        nombre: "Amador Rivas Jr.",
        tipo: "Secundario",
        apodo: "Ojos de pollo",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Estudiante"],
        presidente: false,
        temporadaAparicion: 2,
        frase: ["Javi no tiene ni idea, el hacker soy yo."],
        emoji: "👦👀🐥💻",
    },
    {
        nombre: "Carlota Rivas",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "2º A"],
        piso_contubernio: ["3º Int. Der.", "Fuera"],
        ocupacion: ["Estudiante", "Influencer"],
        presidente: false,
        temporadaAparicion: 1,
        frase: ["¿Vais a echar un pinchito?"],
        emoji: "👧🎭📷👙",
    },
    {
        nombre: "Milagritos",
        tipo: "Episódico",
        apodo: "Abuelita milagritos",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        presidente: false,
        temporadaAparicion: 7,
        frase: ["Espera, espera que me voy a quitar la dentadura..."],
        emoji: "",
    },
    {
        nombre: "Victoria Rafaela",
        tipo: "Principal",
        apodo: "Marquesa",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["1º Ext. Izq.", "3º Ext. Der."],
        ocupacion: ["Marqués"],
        presidente: false,
        temporadaAparicion: 13,
        frase: ["El dinero no es ningún problema para mí."],
        emoji: "👵👑💵",
    }
];

