const antiguosPersonajes = [
    {
        nombre: "Amador Rivas",
        tipo: "Principal",
        apodo: "Cuqui",
        genero: ["Masculino"],
        hijos: 5,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Garaje", "Caravana", "Bajo A", "1º B", "2º A"],
        piso_contubernio: ["3º Int. Der.", "3º Int. Izq."],
        ocupacion: ["Banquero", "Gigoló", "Vendedor", "Vigilante", "Payaso", "Desempleado", "Hombre florero", "Varios trabajos"],
        temporadaAparicion: 1,
        frase: ["¡Si no tengo ganas de na, ¡Na más que de morirme!"],
        emoji: "🦁🕺🕵️‍♂️🦸‍♂️",
    },
    {
        nombre: "Maite Figueroa",
        tipo: "Principal",
        apodo: "Cuqui",
        genero: ["Femenino"],
        hijos: 4,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "1º A", "2º A"],
        piso_contubernio: ["2º Ext. Izq."],
        ocupacion: ["Vendedor", "Masajista", "Escritor", "Ladrón", "Exconvicto", "Camarera"],
        temporadaAparicion: 1,
        frase: ["¡Me caigo muerta!"],
        emoji: "👩🏼🦔🤰👚",
    },
    {
        nombre: "Teodoro Rivas",
        tipo: "Principal",
        apodo: "DJ Theo",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Bajo A", "1º C", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Pescadero", "DJ", "Vendedor"],
        temporadaAparicion: 7,
        frase: ["¡Te voy a poner slim philippine!"],
        emoji: "🎧🦽🪩💿",
    },
    {
        nombre: "Justiniana Latorre",
        tipo: "Secundario",
        apodo: "Maitechu",
        genero: ["Femenino"],
        hijos: 12,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Bajo A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 5,
        frase: ["Maitechu, lo que tienes que hacer es volver con mi hijo."],
        emoji: "👵💶🤬✋",
    },
    {
        nombre: "Antonio Recio",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Caravana", "Bajo B", "1º C"],
        piso_contubernio: ["Bajo Int. Izq.", "3º Ext. Izq."],
        ocupacion: ["Pescadero", "Empresario", "Marqués"],
        temporadaAparicion: 1,
        frase: ["En esta comunidad, ¡Yo soy la ley!"],
        emoji: "🦞🚛🔌🔫",
    },
    {
        nombre: "Berta Escobar",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["1º C", "2º C"],
        piso_contubernio: ["Bajo Int. Izq.", "3º Ext. Izq."],
        ocupacion: ["Pescadero", "Monja", "Ama de casa"],
        temporadaAparicion: 1,
        frase: ["¡Arderéis en el caldero de Satán!"],
        emoji: "⛪️🛐👩‍❤️‍👩👩🏼‍❤️‍💋‍👨🏿",
    },
    {
        nombre: "Alba Recio",
        tipo: "Principal",
        apodo: "Alvaro Recio",
        genero: ["Masculino", "Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Bajo B", "1º C", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Repostería [Oficio/Servicio]", "Monja"],
        temporadaAparicion: 8,
        frase: ["¡¡¡Jurásica, Neandertala, Pleistocénica!!!"],
        emoji: "🏳‍⚧🧁👩🏻🍰",
    },
    {
        nombre: "Violeta Recio",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º C"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Pescadero", "Monja", "Internada"],
        temporadaAparicion: 2,
        frase: ["¿Una limosna para los pobres del mundo?"],
        emoji: "🔪🤪💊🛸",
    },
    {
        nombre: "Rosario Parrales",
        tipo: "Secundario",
        apodo: "Parrales",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Colombia",
        piso_montepinar: ["Fuera", "1º C"],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Pescadero", "Varios trabajos", "Empresario"],
        temporadaAparicion: 4,
        frase: ["¡Es el sueño español!"],
        emoji: "🇨🇴🦐🚛👰🏽‍♂",
    },
    {
        nombre: "Mamasita Parrales",
        tipo: "Esporádico",
        apodo: "Luz Marina Montoya",
        genero: ["Femenino"],
        hijos: 1,
        origen: "Colombia",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Exconvicto", "Traficante"],
        temporadaAparicion: 5,
        frase: ["¡Ay virgencita, me va a hacer vudú!"],
        emoji: "🇨🇴🛫👵🏾💩",
    },
    {
        nombre: "Manolita",
        tipo: "Episódico",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "Colombia",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Ladrón", "Desempleado"],
        temporadaAparicion: 5,
        frase: ["Ay muchas gracias, es tan generoso centollito..."],
        emoji: "🇨🇴👯‍♀💶👩🏽",
    },
    {
        nombre: "Javier Maroto",
        tipo: "Principal",
        apodo: "Pelocho",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º B", "Ático B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Informático", "Conserje"],
        temporadaAparicion: 1,
        frase: ["Ay Lola, Lola, tu nombre me mola..."],
        emoji: "👨‍💻🧑🏻‍🦱👩🏼‍💼🥚",
    },
    {
        nombre: "Lola Trujillo",
        tipo: "Principal",
        apodo: "Chihuaha",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Ático B"],
        piso_contubernio: ["1º Int. Der.", "2º Ext. Izq."],
        ocupacion: ["Fotógrafo", "Actor"],
        temporadaAparicion: 1,
        frase: ["¡Quita, egoista, me he enfadado!"],
        emoji: "🧛‍♀📸🎭🎥",
    },
    {
        nombre: "Vicente Maroto",
        tipo: "Principal",
        apodo: "Hombre cojín",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["2º B", "Ático B"],
        piso_contubernio: ["2º Int. Izq."],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 1,
        frase: ["Eehh, ¡Caña aquí!"],
        emoji: "🛋📺⚽🍺",
    },
    {
        nombre: "Estela Reynolds",
        tipo: "Principal",
        apodo: "Paca Pacheco",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo A", "Ático B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Actor"],
        temporadaAparicion: 3,
        frase: ["¡Oh! ¡Qué ataque más gratuito!"],
        emoji: "🥃🎭📽🥴",
    },
    {
        nombre: "Fermín Trujillo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º B", "Ático B"],
        piso_contubernio: ["2º Int. Der.", "3º Ext. Der."],
        ocupacion: ["Espetero", "Camarero", "Empresario", "Payaso", "Conserje"],
        temporadaAparicion: 6,
        frase: ["To las locas del coño, ¡pa mí!"],
        emoji: "🐟🛶👨🍺",
    },
    {
        nombre: "Gregoria Gutiérrez",
        tipo: "Principal",
        apodo: "Doña Croqueta",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["2º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 1,
        frase: ["¡Marido cojín!"],
        emoji: "👩‍🍳🥘⚰👩‍🦱",
    },
    {
        nombre: "Martina",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Ático B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Masajista", "Terapeuta"],
        temporadaAparicion: 11,
        frase: ["Tu cuerpo te esta hablando..."],
        emoji: "👩💆‍♀️🤱👨🏻‍🦱",
    },
    {
        nombre: "Gabi",
        tipo: "Esporádico",
        apodo: "Javi",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Informático", "Empresario"],
        temporadaAparicion: 7,
        frase: ["¡Easy date es todo un éxito!"],
        emoji: "🤑💻💪😁",
    },
    {
        nombre: "Enrique Pastor",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo B", "Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        temporadaAparicion: 1,
        frase: ["Aquí hay tema... ¡Pero vamos!"],
        emoji: "👨🏻‍🦲📚🏛️🐬",
    },
    {
        nombre: "Araceli Madariaga",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B", "1º C", "2º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Peluquero", "Masajista", "Ama de casa"],
        temporadaAparicion: 1,
        frase: ["Yo me enamoro de almas, no de genitales..."],
        emoji: "👩‍❤️‍👩🍃🕉️🇳🇵",
    },
    {
        nombre: "Judith Becker",
        tipo: "Principal",
        apodo: "Cuchufleta",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B", "Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Psicólogo"],
        temporadaAparicion: 3,
        frase: ["No atiendo sin cita previa..."],
        emoji: "👩‍🦰👴🏻👩‍⚕🦒",
    },
    {
        nombre: "Reyes Ballesteros",
        tipo: "Principal",
        apodo: "Lesbiana",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Dentista"],
        temporadaAparicion: 5,
        frase: ["Este mundo está lleno de homófobos de mierda."],
        emoji: "🦷👩‍🦰💪🏳‍🌈",
    },
    {
        nombre: "Julián Pastor",
        tipo: "Secundario",
        apodo: "Viejo verde",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Bajo B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 1,
        frase: ["Tu deja los estudios a un lado lo más importante ahora es que pierdas tu virginidad."],
        emoji: "👴🏻🦽👯‍♀💶",
    },
    {
        nombre: "Matthew Edwards",
        tipo: "Esporádico",
        apodo: "Fuck fuck fuck",
        genero: ["Masculino"],
        hijos: 2,
        origen: "Estados Unidos",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 4,
        frase: ["Quitó camiseto, y tenia pezones duros como piedros..."],
        emoji: "🇺🇸👨🏼‍🦱☠🇵🇭",
    },
    {
        nombre: "Menchu Carrascosa",
        tipo: "Principal",
        apodo: "Tanqueta",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Ático A"],
        piso_contubernio: ["1º Ext. Der.", "3º Int. Izq."],
        ocupacion: ["Jubilado", "Ama de casa", "Traficante"],
        temporadaAparicion: 9,
        frase: ["¡Cómeme las tetas!"],
        emoji: "👩🛒🍳👜",
    },
    {
        nombre: "Yolanda Morcillo",
        tipo: "Principal",
        apodo: "Yoli Morcillo",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Ático A", "2º A"],
        piso_contubernio: ["1º Ext. Der.", "3º Int. Izq."],
        ocupacion: ["Diseñador", "Traficante", "Influencer"],
        temporadaAparicion: 9,
        frase: ["¡Que yo estoy enamorada, y cuando estoy enamorada soy MUY peligrosa!"],
        emoji: "👩🛍👗🧵",
    },
    {
        nombre: "Josito Morcillo",
        tipo: "Secundario",
        apodo: "José Morcillo",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera", "Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desempleado", "Traficante"],
        temporadaAparicion: 9,
        frase: ["¿Te gusta el porno? Tengo 4 teras."],
        emoji: "✖📁💻🧻",
    },
    {
        nombre: "Moroso",
        tipo: "Secundario",
        apodo: "Germán Palomares",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º C"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 1,
        frase: ["Vecinos, iros a tomar por culo."],
        emoji: "👤❓💰💼",
    },
    {
        nombre: "Fina Palomares",
        tipo: "Principal",
        apodo: "Doña Fina",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["2º C"],
        piso_contubernio: ["2º Int. Der."],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 8,
        frase: ["¡¿Qué hablais de mí?!"],
        emoji: "🪑👵🏻🐈😈",
    },
    {
        nombre: "Clarita Gutiérrez",
        tipo: "Principal",
        apodo: "Clara Gutiérrez",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera", "2ºA"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Conserje", "Sirviente", "Pescadero", "Desempleado"],
        temporadaAparicion: 10,
        frase: ["Es que si no me lo explicas bien…"],
        emoji: "👩🧹🤱🛒",
    },
    {
        nombre: "Nines Chacón",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Sirviente", "Camarero", "Desempleado"],
        temporadaAparicion: 2,
        frase: ["¡No ni ná!"],
        emoji: "🤰🛋📺💃",
    },
    {
        nombre: "Raquel Villanueva",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor", "Camarero", "Wedding planner"],
        temporadaAparicion: 1,
        frase: ["¡Que no son operadas!"],
        emoji: "👩🏼‍💼🍈🍈💍",
    },
    {
        nombre: "Rebeca Ortiz",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Ático A"],
        piso_contubernio: ["1º Ext. Der."],
        ocupacion: ["Abogado"],
        temporadaAparicion: 7,
        frase: ["Yo te llevo el divorcio."],
        emoji: "👱‍♀👩🏼‍💼👩🏼‍⚖💼",
    },
    {
        nombre: "Blanca Neruda",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        temporadaAparicion: 2,
        frase: ["Si me subes el correo te recibo en lencería."],
        emoji: "👩💼👢👙",
    },
    {
        nombre: "Coque Calatrava",
        tipo: "Principal",
        apodo: "Coke",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Caravana", "Bajo B", "1º A"],
        piso_contubernio: ["Portería"],
        ocupacion: ["Jardinero", "Conserje", "Camarero", "Yonki", "Cómico"],
        temporadaAparicion: 1,
        frase: ["Una cosilla que se me viene a la mente..."],
        emoji: "🌲🚬🧹🩻",
    },
    {
        nombre: "Maxi Angulo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Caravana", "Bajo B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Conserje", "Camarero"],
        temporadaAparicion: 1,
        frase: ["¡Atrás! ¡No me obligues a hacerte el molinillo!"],
        emoji: "🦁🍻🧠🥶",
    },
    {
        nombre: "José Ignacio",
        tipo: "Esporádico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Abogado"],
        temporadaAparicion: 7,
        frase: ["Este juicio esta ganado A-Arturo, Amador."],
        emoji: "👨‍⚖💼📄📃",
    },
    {
        nombre: "Mari Tere Valverde",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 3,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 1,
        frase: ["Te he preparado un bizcocho."],
        emoji: "👵🎂🗣📓",
    },
    {
        nombre: "Izaskun Sagastume",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo A", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 1,
        frase: ["¡Movida, movida!"],
        emoji: "🚬👵🥃📓",
    },
    {
        nombre: "Bruno Quiroga",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Bajo B", "1º B"],
        piso_contubernio: ["3º Ext. Der."],
        ocupacion: ["Pianista", "Artista"],
        temporadaAparicion: 9,
        frase: ["¡Que me hizo un Boris Becker!"],
        emoji: "🤵🎹🎶🏆",
    },
    {
        nombre: "Cristina Aguilera",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        temporadaAparicion: 1,
        frase: ["Soy comercial de una agencia de viajes, no prostituta."],
        emoji: "",
    },
    {
        nombre: "Leonardo Romaní",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["1º B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor", "Empresario"],
        temporadaAparicion: 1,
        frase: ["Que me debes 50000€ euros."],
        emoji: "🤓🎮💰💻",
    },
    {
        nombre: "Ongombo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "África",
        piso_montepinar: ["1º C"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Conserje", "Pescadero", "Sirviente"],
        temporadaAparicion: 10,
        frase: ["¡Tu culo de negra, eh!"],
        emoji: "🇨🇬👨🏿💪🏿👩🏼‍❤‍💋‍👨🏿",
    },
    {
        nombre: "Sergio Arias",
        tipo: "Principal",
        apodo: "Doctor Ventura",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo A", "Ático A"],
        piso_contubernio: ["3º Ext. Der."],
        ocupacion: ["Actor"],
        temporadaAparicion: 1,
        frase: ["¿Ves esa estrella? Ahora lleva tu nombre."],
        emoji: "🎥🕴👨‍⚕🩺",
    },
    {
        nombre: "Joaquin Arias",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Ático A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        temporadaAparicion: 1,
        frase: ["Habléme sin tapujos Doctor Ventura..."],
        emoji: "",
    },
    {
        nombre: "Bibiana",
        tipo: "Esporádico",
        apodo: "Travesti",
        genero: ["Masculino", "Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Prostituta"],
        temporadaAparicion: 8,
        frase: ["El tiburón no me lo corto porque es mi herramienta de trabajo"],
        emoji: "🧔🏼‍♀👮‍♂🏳‍⚧⚧",
    },
    {
        nombre: "Agustín Gordillo",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º A"],
        piso_contubernio: ["3º Int. Der."],
        ocupacion: ["vendedor de filtros de agua"],
        temporadaAparicion: 11,
        frase: ["Lo veo todo por un agujerito."],
        emoji: "👷‍♂️👩‍⚕️👨‍🏭👨‍⚕️",
    },
    {
        nombre: "Alcaldesa",
        tipo: "Secundario",
        apodo: "María Teresa",
        genero: ["Femenino"],
        hijos: 3,
        origen: "España",
        piso_montepinar: ["Fuera", "Bajo B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        temporadaAparicion: 8,
        frase: ["¡Fuera pajarraco malo, fuera!"],
        emoji: "👵🏻🏛🐦‍⬛👜",
    },
    {
        nombre: "Señor ministro",
        tipo: "Esporádico",
        apodo: "Alejandro Echevarria",
        genero: ["Masculino"],
        hijos: 3,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        temporadaAparicion: 8,
        frase: ["Enrique, me has fallado 3 veces, no me falles 4..."],
        emoji: "🤵💼💿🏛️",
    },
    {
        nombre: "Raluca Petrescu",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "Rumanía",
        piso_montepinar: ["Fuera", "Bajo A", "Ático B"],
        piso_contubernio: ["2º Int. Der."],
        ocupacion: ["Prostituta", "Pescadera", "Masajista", "Sirviente"],
        temporadaAparicion: 6,
        frase: ["¡Ay, Fermín! '¡hasme tulia' otra vez!"],
        emoji: "🇷🇴🚺🍔🍕",
    },
    {
        nombre: "Chusa",
        tipo: "Principal",
        apodo: "La Chusa",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "Bajo A", "Ático A"],
        piso_contubernio: ["3º Ext. Izq.", "1º Int. Der."],
        ocupacion: ["Prostituta", "Yonki", "Sirviente"],
        temporadaAparicion: 4,
        frase: ["¡¿A qué te pincho?!"],
        emoji: "🔪💉💸👯‍♀",
    },
    {
        nombre: "Cabeza nido",
        tipo: "Secundario",
        apodo: "Héctor",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "Bajo A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Artista", "Hombre florero"],
        temporadaAparicion: 9,
        frase: ["Voy a hacer mi opera prima: 'El hombre y la mierda'."],
        emoji: "👤🪹🎨👨‍🎨",
    },
    {
        nombre: "Cecilio el terapeuta",
        tipo: "Esporádico",
        apodo: "Argentino",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Argentina",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Psicólogo", "Terapeuta"],
        temporadaAparicion: 7,
        frase: ["Tienes que abrazar tu soledad iluminadora..."],
        emoji: "🇦🇷👨‍⚕📝🤔",
    },
    {
        nombre: "Rosanna",
        tipo: "Secundario",
        apodo: "Rosana",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Prostituta"],
        temporadaAparicion: 11,
        frase: ["Mejor damelo todo en cash que esto me pilla muy lejos."],
        emoji: "",
    },
    {
        nombre: "Padre Alejandro",
        tipo: "Secundario",
        apodo: "Alejandro Ledesma",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Sacerdote"],
        temporadaAparicion: 5,
        frase: ["¡Antonio has metido un arma en la casa del señor!"],
        emoji: "⛪🙏👬👨‍❤️‍💋‍👨",
    },
    {
        nombre: "Mario Vaquerizo",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Actor", "Representante"],
        temporadaAparicion: 6,
        frase: ["Venga cariño, tira la foto que tengo prisa..."],
        emoji: "",
    },
    {
        nombre: "Pascual",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vigilante"],
        temporadaAparicion: 2,
        frase: ["¡Violación del perímetro!"],
        emoji: "🔫👮🏻‍♂👆🔪",
    },
    {
        nombre: "Edurne Sagastume",
        tipo: "Esporádico",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera", "2º A"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 7,
        frase: ["Te voy a echar un polvo que te voy a doblar."],
        emoji: "",
    },
    {
        nombre: "Naserbin Khalid Al-Faisal",
        tipo: "Episódico",
        apodo: "Jeque árabe",
        genero: ["Masculino"],
        hijos: 1,
        origen: "Árabe",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jeque", "Traficante"],
        temporadaAparicion: 3,
        frase: ["Nice to meet you Antonio my friend!"],
        emoji: "🕌🇦🇪👳🏾‍♂💰",
    },
    {
        nombre: "Maharamindri Baba",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Argentina",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Sacerdote"],
        temporadaAparicion: 3,
        frase: ["¡¿Hermanos oís la voz?!"],
        emoji: "🇦🇷🙏💰🛸",
    },
    {
        nombre: "Miguel",
        tipo: "Esporádico",
        apodo: "Director internado sangriento",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Director"],
        temporadaAparicion: 4,
        frase: ["¿Amigo yo? ¿De un actor?"],
        emoji: "👨😡🎬🎭",
    },
    {
        nombre: "Minguito",
        tipo: "Secundario",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Villazarcillo", "Fuera"],
        piso_contubernio: ["3º Ext. Izq."],
        ocupacion: ["Desempleado", "Conserje"],
        temporadaAparicion: 9,
        frase: ["¡Te desafío!"],
        emoji: "",
    },
    {
        nombre: "Carmelito",
        tipo: "Esporádico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Hijo putaaa... me has mataooo..."],
        piso_contubernio: ["3º Ext. Izq.", "1º Int. Der."],
        ocupacion: ["Yonki"],
        temporadaAparicion: 7,
        emoji: "",
    },
    {
        nombre: "Suliman",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "África",
        piso_montepinar: ["Fuera"],
        frase: ["¡Fermín cabrón! Tu debes 20€"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        temporadaAparicion: 6,
        emoji: "",
    },
    {
        nombre: "Ramón Rivas",
        tipo: "Esporádico",
        apodo: "Padre amador",
        genero: ["Masculino"],
        hijos: 12,
        origen: "España",
        piso_montepinar: ["Villazarcillo"],
        frase: ["Amador, soy gay."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 5,
        emoji: "",
    },
    {
        nombre: "Fabio Sabatani",
        tipo: "Esporádico",
        apodo: "Peluquero",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Argentina",
        piso_montepinar: ["Fuera"],
        frase: ["Se me deprimió la becaria..."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Peluquero"],
        temporadaAparicion: 1,
        emoji: "👨💈✂🇦🇷",
    },
    {
        nombre: "Silvio",
        tipo: "Principal",
        apodo: "Okupa",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Cuba",
        piso_montepinar: ["1º A"],
        frase: ["¡Ay, Chocho!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Camarero", "Desempleado"],
        temporadaAparicion: 1,
        emoji: "👬🏳️‍🌈🛍🐕",
    },
    {
        nombre: "Hakim",
        tipo: "Episódico",
        apodo: "Marroquí",
        genero: ["Masculino"],
        hijos: 0,
        origen: "Árabe",
        piso_montepinar: ["Fuera"],
        frase: ["Perdone señor, pero no tengo que aguantar su intolerancia."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 3,
        emoji: "",
    },
    {
        nombre: "Eric Cortés",
        tipo: "Secundario",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Mujeres hay muchas, hermanos solo tienes uno."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Vendedor"],
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Sandra Espinosa",
        tipo: "Secundario",
        apodo: "Becaria",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Araceli, la señora del secador no se mueve..."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Peluquero", "Camarero", "Prostituta"],
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Charo",
        tipo: "Secundario",
        apodo: "Doña Charo",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B"],
        frase: ["¡Qué no hay papel!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Barbara",
        tipo: "Secundario",
        apodo: "Teacher cajadientes",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["¡Dame más duro contra el mapa de España!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Profesor"],
        temporadaAparicion: 10,
        emoji: "👩‍🏫🦷🗺👦",
    },
    {
        nombre: "Sonia",
        tipo: "Esporádico",
        apodo: "La klingon",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "2º C"],
        frase: ["Tu hijo me ha quemado el pelo, los niños me llaman la Freddy Krueger."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Profesor"],
        temporadaAparicion: 10,
        emoji: "👩‍🏫🧪🥼🙍‍♀️",
    },
    {
        nombre: "Gigi Diamond",
        tipo: "Episódico",
        apodo: "Marta",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["¡No! Llámame Marta, ____ es un nombre demasiado sucio para que lo utilice mi novio..."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Actriz"],
        temporadaAparicion: 5,
        emoji: "🎭👠💎💎",
    },
    {
        nombre: "Tomás",
        tipo: "Esporádico",
        apodo: "Gay Lola",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["¡Nosotras parimos, nosotras decidimos!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Estilista", "Representante"],
        temporadaAparicion: 3,
        emoji: "🎭🏳️‍🌈👬💄",
    },
    {
        nombre: "Alcalde",
        tipo: "Secundario",
        apodo: "Juan Antonio Valbuena",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Te presento a mi perro, Jose Mari"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Político"],
        temporadaAparicion: 3,
        emoji: "🤵🐕🏛️⛓",
    },
    {
        nombre: "Luis Ángel",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["2º C"],
        frase: ["¿Cuando os he dicho que me iba a la India?"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Informático"],
        temporadaAparicion: 3,
        emoji: "👨💻🧳🇮🇳",
    },
    {
        nombre: "Francisco Javier",
        tipo: "Principal",
        apodo: "Fran",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Bajo B"],
        frase: ["¡Cómeme el rabo!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Estudiante", "Camarero"],
        temporadaAparicion: 1,
        emoji: "🚬☘🛵👦🏻",
    },
    {
        nombre: "Patu",
        tipo: "Esporádico",
        apodo: "Tetas de goma",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Maite, conozco un abogado buenísimo."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Ama de casa"],
        temporadaAparicion: 1,
        emoji: "👩🍈🍈💃",
    }
];

const nuevosPersonajes = [
    {
        nombre: "Fidel Morcillo",
        tipo: "Esporádico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["No he visto Dumbo, ¿Quién es?"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 9,
        emoji: "👴🛋🍳🚫",
    },
    {
        nombre: "Amador Rivas Jr.",
        tipo: "Secundario",
        apodo: "Ojos de pollo",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "2º A"],
        frase: ["Javi no tiene ni idea, el hacker soy yo."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Estudiante"],
        temporadaAparicion: 2,
        emoji: "👦👀🐥💻",
    },
    {
        nombre: "Carlota Rivas",
        tipo: "Secundario",
        apodo: "",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "2º A"],
        frase: ["¿Vais a echar un pinchito?"],
        piso_contubernio: ["3º Int. Der.", "Fuera"],
        ocupacion: ["Estudiante", "Influencer"],
        temporadaAparicion: 1,
        emoji: "👧🎭📷👙",
    },
    {
        nombre: "Fernando Rivas",
        tipo: "Secundario",
        apodo: "Nano",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "2º A"],
        frase: ["¿Vais a hacer el amoooor?"],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Estudiante"],
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Rodrigo Rivas",
        tipo: "Secundario",
        apodo: "Nano",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Garaje", "Bajo A", "2º A"],
        frase: ["Gañán, putón, gañán, putón, gañán, putón, ..."],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Futbolista", "Estudiante"],
        temporadaAparicion: 1,
        emoji: "",
    },
    {
        nombre: "Matías",
        tipo: "Episódico",
        apodo: "Presidente de Atalaya del Arcipreste",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Atalaya del Arcipeste"],
        frase: ["Bienvenido a la atalaya del arcipreste"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Presidente de la comunidad"],
        temporadaAparicion: 4,
        emoji: "🏦📡🌩👨",
    },
    {
        nombre: "Katiuska",
        tipo: "Esporádico",
        apodo: "Rusa",
        genero: ["Femenino"],
        hijos: 0,
        origen: "Rusia",
        piso_montepinar: ["Fuera", "1º C"],
        frase: ["No la dejamos aquí, ¡Mi padre mata!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Camarera", "Pescadera"],
        temporadaAparicion: 10,
        emoji: "👱‍♀️🏨❄🇷🇺",
    },
    {
        nombre: "Diego Tejada",
        tipo: "Esporádico",
        apodo: "Jamoncitos",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["No, ¡Guapa tú mamá!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Empresario"],
        temporadaAparicion: 8,
        emoji: "💵👵🐷🇨🇳",
    },
    {
        nombre: "Maria Josefa Rivas",
        tipo: "Esporádico",
        apodo: "Marijose, hermana fea de Amador",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Villazarcillo"],
        frase: ["Como alguien vuelva a llamarme fea, ¡Me rajo!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Ama de casa"],
        temporadaAparicion: 7,
        emoji: "",
    },
    {
        nombre: "Patricia",
        tipo: "Secundario",
        apodo: "Asistenta niños",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Maite, los niños se están adaptando a la casa de acogida."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Asistente social"],
        temporadaAparicion: 8,
        emoji: "",
    },
    {
        nombre: "Mercedes",
        tipo: "Secundario",
        apodo: "Asistenta niños",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Usted me folla, y yo redacto un informe favorable para que le devuelvan a sus hijos."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Asistente social"],
        temporadaAparicion: 9,
        emoji: "",
    },
    {
        nombre: "Martillo Smith",
        tipo: "Episódico",
        apodo: "Boxeador",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["¡Yo tengo que entrenar, o lo hago con el saco, o lo hago con vosotros!"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Boxeador"],
        temporadaAparicion: 6,
        emoji: "👨🔨🥊😡",
    },
    {
        nombre: "Flora",
        tipo: "Episódico",
        apodo: "Como la margarina",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["La universidad es un paripé del sistema para tenerte aniestesado 5 años sin englosar la lista del paro."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Estudiante", "Desempleado"],
        temporadaAparicion: 7,
        emoji: "👩🎒🐂☮",
    },
    {
        nombre: "Eduardo Pastor",
        tipo: "Episódico",
        apodo: "Hermano de Enrique",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Cuando quieras trabajo, me llamas y te pongo a repartir bocadillos"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Empresario"],
        temporadaAparicion: 1,
        emoji: "👨🥪💵👴",
    },
    {
        nombre: "Manolo72",
        tipo: "Episódico",
        apodo: "Candidato maite",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Fue el que me consiguió la cita contigo, que eras una guarra... Pinchito seguro."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 5,
        emoji: "🕺7️⃣2️⃣🎉",
    },
    {
        nombre: "Sussy Pussy",
        tipo: "Episódico",
        apodo: "Susi pusi, Angelines",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Ah, ¿Había que traerse un nombre artístico?"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desempleado", "Actriz"],
        temporadaAparicion: 5,
        emoji: "",
    },
    {
        nombre: "Milagritos",
        tipo: "Episódico",
        apodo: "Abuelita milagritos",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Espera, espera que me voy a quitar la dentadura..."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Jubilado"],
        temporadaAparicion: 7,
        emoji: "",
    },
    {
        nombre: "Trevor Simons",
        tipo: "Esporádico",
        apodo: "Novio Judith",
        genero: ["Masculino"],
        hijos: 1,
        origen: "Estados Unidos",
        piso_montepinar: ["Fuera"],
        frase: ["Oye cuanta gente para recibirme, me siento Obama."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 7,
        emoji: "👨👩‍🦰🏃‍♂️🇺🇲",
    },
    {
        nombre: "Megan Simons",
        tipo: "Esporádico",
        apodo: "Novio Judith",
        genero: ["Femenino"],
        hijos: 1,
        origen: "Estados Unidos",
        piso_montepinar: ["Fuera"],
        frase: ["Yo soy muy contenta que tu come aquí."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 8,
        emoji: "👩👩‍🌾👢🇺🇲",
    },
    {
        nombre: "Ferran Barreiros",
        tipo: "Esporádico",
        apodo: "Percebesa",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        frase: ["Enhorabuena Antonio, que por fin estás nominado al Bogavante de Oro."],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Empresario"],
        temporadaAparicion: 5,
        emoji: "👨🥇🏆🦞",
    },
    {
        nombre: "Sor Pepita",
        tipo: "Esporádico",
        apodo: "Monja",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Monja"],
        temporadaAparicion: 6,
        frase: ["Por el amor de Dios, ¿Cóomo iba a robar yo, a un recién nacido?"],
        emoji: "👵💰👶✝",
    },
    {
        nombre: "Clemencia",
        tipo: "Episódico",
        apodo: "Monja, amiga de Berta",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "Bajo B"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Monja", "Ama de casa"],
        temporadaAparicion: 8,
        frase: ["Nunca había pensado demasiado en los hombres eh, no soy una libertina."],
        emoji: "",
    },
    {
        nombre: "Gloria",
        tipo: "Esporádico",
        apodo: "Ex bruno",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Enfermero", "Jubilada"],
        temporadaAparicion: 9,
        frase: ["Como me llame amor mío, me voy."],
        frase: ["¿Que qué ha pasado? Llevo 12 años de mi vida saliendo con un ser inmaduro, egocéntrico, maniático, manipulador, [...], y no lo soporto más."],
        emoji: "",
    },
    {
        nombre: "Pilar",
        tipo: "Secundario",
        apodo: "Madre de Berta",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Empresario", "Jubilada"],
        temporadaAparicion: 3,
        frase: ["¡Hija, si es que tendrías que haberte casado con Hilario, el de los cementos!"],
        emoji: "💎🔫👵💰",
    },
    {
        nombre: "Ingrid Becker",
        tipo: "Esporádico",
        apodo: "Hermana Judith",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["3º Ext. Der."],
        ocupacion: ["Psicólogo"],
        temporadaAparicion: 4,
        frase: ["Judith, no compitas..."],
        emoji: "",
    },
    {
        nombre: "Señor Xong",
        tipo: "Episódico",
        apodo: "Zuzu, Empresario Chino",
        genero: ["Masculino"],
        hijos: 0,
        origen: "China",
        piso_montepinar: ["Fuera"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Empresario", "Político"],
        temporadaAparicion: 9,
        frase: ["Araceli, 让我吸你的脚趾。"],
        emoji: "💰🎲😑🇨🇳",
    },
    {
        nombre: "Penélope",
        tipo: "Episódico",
        apodo: "Enfermera asesina",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["Fuera", "2ºB"],
        piso_contubernio: ["No aparece"],
        ocupacion: ["Enfermero"],
        temporadaAparicion: 7,
        frase: ["Pero qué quejicas sois todos los viejos, ¡Si te hubieras roto algo estarías rabiando!"],
        emoji: "👩‍⚕️🔪👴👵",
    },
]

const contubernioPersonajes = [
    {
        nombre: "Andrea Quirón",
        tipo: "Principal",
        apodo: "Les chiques, Andy",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Bajo Int. Izq."],
        ocupacion: ["Camarero"],
        temporadaAparicion: 13,
        frase: ["Amador, deja el croissant"],
        emoji: "",
    },
    {
        nombre: "Jorge Verdugo",
        tipo: "Principal",
        apodo: "Les chiques, Giorgi",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Bajo Int. Izq."],
        ocupacion: ["Pescadero"],
        temporadaAparicion: 13,
        frase: ["Si tiene un bukake, coge fuerzas con un rape"],
        emoji: "",
    },
    {
        nombre: "Karma",
        tipo: "Principal",
        apodo: "Les chiques",
        genero: ["Masculino", "Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Bajo Int. Izq."],
        ocupacion: ["Canguro"],
        temporadaAparicion: 13,
        frase: ["Soy una instagramer omnisexual"],
        emoji: "",
    },
    {
        nombre: "Victoria Rafaela Balmaseda de Unzeta y Téllez-Girón",
        tipo: "Principal",
        apodo: "Marquesa",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["1º Ext. Izq.", "3º Ext. Der."],
        ocupacion: ["Marqués"],
        temporadaAparicion: 13,
        frase: ["El dinero no es ningún problema para mí."],
        emoji: "👵👑💵✖",
    },
    {
        nombre: "Eulogia Sarrión",
        tipo: "Principal",
        apodo: "Logi",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["1º Ext. Izq.", "3º Ext. Der."],
        ocupacion: ["Ama de casa"],
        temporadaAparicion: 13,
        frase: ["Señora, el vídeoclub lo cerraron hace 10 años."],
        emoji: "👵🧹🗣👑",
    },
    {
        nombre: "Remedios Infante",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Int. Izq."],
        ocupacion: ["Cuidadora", "Jubilada"],
        temporadaAparicion: 13,
        frase: ["Suelta eso estrambótico"],
        emoji: "",
    },
    {
        nombre: "Alonso Martínez",
        tipo: "Principal",
        apodo: "Alons",
        genero: ["Masculino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Izq."],
        ocupacion: ["Empresario", "Vendedor"],
        temporadaAparicion: 13,
        frase: ["Cieluchi deberías llevarte bien con Inma por los niños."],
        emoji: "🛏💰🩲👨",
    },
    {
        nombre: "Greta Garmendia",
        tipo: "Principal",
        apodo: "La thunber",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Der."],
        ocupacion: ["Farmacéutica"],
        temporadaAparicion: 13,
        frase: ["No pasa nada, soy una persona con un gran sentido del humor, a pesar de tener un palo de fregona metido por el culo."],
        emoji: "👩‍⚕️💊🦌👪",
    },
    {
        nombre: "Esteban Guijarro",
        tipo: "Principal",
        apodo: "",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Der."],
        ocupacion: ["Inspector de hacienda"],
        temporadaAparicion: 13,
        frase: ["Yo mientras no se drogue..."],
        emoji: "🤵💰💼🩲",
    },
    {
        nombre: "Julia Guijarro Garmendia",
        tipo: "Principal",
        apodo: "",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["2º Ext. Der."],
        ocupacion: ["Estudiante"],
        temporadaAparicion: 13,
        frase: ["Vosotros decidistéis comprar mi virginidad, quiero el bajo a mi nombre"],
        emoji: "",
    },
    {
        nombre: "Noelia Federica Balmaseda de Unzeta y Téllez-Girón",
        tipo: "Principal",
        apodo: "Hermana Marquesa",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["3º Ext. Izq."],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 13,
        frase: ["¡¿Qué pasa?!, ¡Que solo me iba a planchar una blusa!"],
        emoji: "",
    },
    {
        nombre: "Óscar Serra",
        tipo: "Principal",
        apodo: "Follográfo",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["1º Ext. Der", "3º Int. Izq."],
        ocupacion: ["Fotógrafo", "Modelo"],
        temporadaAparicion: 13,
        frase: ["Menchu, acepto, quiero que me adoptes"],
        emoji: "📷👨🎱🕹",
    },
    {
        nombre: "Modesto",
        tipo: "Episódico",
        apodo: "",
        genero: ["Masculino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Portería"],
        ocupacion: ["Conserje"],
        temporadaAparicion: 13,
        frase: ["Trabajo en el edificio de Contubernio 49 desde hace más de 47 años."],
        emoji: "👴☠🧹📖",
    },
    {
        nombre: "Manoli Prieto",
        tipo: "Episódico",
        apodo: "Amiga gorda de Yoli",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 13,
        frase: ["Defendemos la revolución de la raza y el fin de la gordofobia."],
        emoji: "",
    },
    {
        nombre: "Xiang Li",
        tipo: "Secundario",
        apodo: "Camarero Chino",
        genero: ["Masculino"],
        hijos: 0,
        origen: "China",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Fuera", "Bajo Int. Izq."],
        ocupacion: ["Cocinero", "Camarero"],
        temporadaAparicion: 14,
        frase: ["Pues caliéntalos en el microondas, gilipollas"],
        emoji: "🍜👨‍🍳😑🇨🇳",
    },
    {
        nombre: "Cristina Sanromán",
        tipo: "Principal",
        apodo: "Mami pechotes",
        genero: ["Femenino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Bajo Int. Der."],
        ocupacion: ["Dentista"],
        temporadaAparicion: 14,
        frase: ["Oye no te me pongas decinómonico eh, que ya te hemos pedido perdón."],
        emoji: "🤱🍼🍼🦷",
    },
    {
        nombre: "Martín Segurola",
        tipo: "Principal",
        apodo: "Cocinillas, tostas",
        genero: ["Masculino"],
        hijos: 1,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Bajo Int. Der."],
        ocupacion: ["Cocinero"],
        temporadaAparicion: 14,
        frase: ["Te dije que era muy pronto para llevarla a la guardería"],
        emoji: "🤒👨‍🍳🍳👶",
    },
    {
        nombre: "Verónica",
        tipo: "Secundario",
        apodo: "Vero, ex de Óscar",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 14,
        frase: ["¿Para qué has comprado un anillo si no te ibas a casar conmigo?"],
        emoji: "",
    },
    {
        nombre: "Inmaculada Mateos-Rellana",
        tipo: "Secundario",
        apodo: "Inma, ex Alons",
        genero: ["Femenino"],
        hijos: 2,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Hippie", "Político"],
        temporadaAparicion: 14,
        frase: ["Practico la orinoterapia, bebo mis propios fluidos"],
        emoji: "",
    },

    {
        nombre: "Natalia",
        tipo: "Secundario",
        apodo: "Novia Agustín",
        genero: ["Femenino"],
        hijos: 0,
        origen: "España",
        piso_montepinar: ["No aparece"],
        piso_contubernio: ["Fuera"],
        ocupacion: ["Desconocido"],
        temporadaAparicion: 14,
        frase: ["No entiendo, que necesidad tienes de ser tan simpático con una ex."],
        emoji: "",
    },
]

export function getCharacters() {
    const personajesLQSA = [
        ...antiguosPersonajes,
        ...nuevosPersonajes,
        ...contubernioPersonajes
    ];
    return personajesLQSA;
}